version: "3.8"

services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
