apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo
spec:
  containers:
    - name: app
      image: busybox:1.28
      command: ['sh', '-c', 'env && sleep 3600']
      envFrom:
        - configMapRef:
            name: app-config

